# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-07 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userdash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login_reg',
            name='confirm_password',
        ),
        migrations.AddField(
            model_name='login_reg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='login_reg',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
